application: sans-titres
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_dir: src
- url: /
  script: Router.app

libraries:
- name: webapp2
  version: "2.5.1"
